name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: macos-latest
    env:
      RUNALL: "true"
    steps:
      - name: Checkout code
        uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c

      - name: Run tests
        run: swift test
